### PR TITLE
Fixed the skipping to revision 2 when creating new capp

### LINKED ISSUE #35: When capp being created it start at generation 2
Right now when we create a new `capp` 2 revisions are being created instead of one.

### PR DESCRIPTION
**Pull request by sahar2339**
Fixed by adding the default values of `knativev1.Service` to the `prepareResource` function to match the Knative defaulting webhook
fixes #35

### CODE REVIEW

**Comment by mzeevi** [comment]
Can you please shed some light here on why this resolves the issue?

**Comment by sahar2339** [comment]
The issue originated from the `CreateOrUpdateObject` function, when deciding if the `knativev1.Service` should be updated we compare the actual resource with the one generated with the `prepareResource` function to check if there was changes in the `capp` resource that should trigger `knativev1.Service' reconcile.
It turns out that `knativev1.Service` was mutated by defaulting webhook or the Knative operator with default values other than ours, and the resource was different.
The `knativev1.Service` updated, creating a new revision.
As I mentioned in the commit message, it fixed by adding the default values to the `prepareResource` so the update won't occur.

**Review by mzeevi — APPROVED** [review]

**Pull request merged**
